ai: 
  enabled: true
  # provider: deepseek      # 支持：ollama, openai, deepseek
  provider: ollama
  max_retries: 3
  model_name: qwen3:1.7b
  # model_name: deepseek-chat
  timeout: 60
  
  # 各提供商的API端点配置 - 消除硬编码，支持多账户
  endpoints:
    ollama:
      base_url: http://localhost:11434      # Ollama服务地址
      chat_endpoint: /api/chat              # 聊天API路径
      api_key: null                         # Ollama不需要API密钥
    openai:
      base_url: https://api.openai.com/v1   # OpenAI API基础URL
      chat_endpoint: /chat/completions      # 聊天API路径
      api_key: your-openai-api-key-here     # OpenAI API密钥
    deepseek:
      base_url: https://api.deepseek.com    # DeepSeek API基础URL
      chat_endpoint: /v1/chat/completions   # 聊天API路径
      api_key: your-deepseek-api-key-here  # DeepSeek API密钥
  
  # AI模型推理参数
  options:
    temperature: 0.0      # 随机性控制，0.0=完全确定性，2.0=高随机性
    top_p: 0.3           # 核采样，控制候选词概率范围
    top_k: 10            # 限制每步考虑的候选词数量
    num_predict: 512     # 限制输出的最大token数量
    max_tokens: 512      # 外部模型使用（对应num_predict）
asr:
  language: zh
  model: fireredasr
  provider: cpu
  sample_rate: 16000
logging:
  format: '%(levelname)s: %(asctime)s %(name)s:%(lineno)s %(message)s'
  level: INFO
  # level: DEBUG
  log_file: null
processing:
  batch_size: 100
  enable_concurrent: false
  threads: 2
server:
  debug: false
  host: localhost
  port: 8000
  auto_reload_config: false  # 是否启用配置文件自动重载监听
storage:
  auto_backup: true
  download_dir: ./download
  export_excel: true
  models_dir: ./models
tts:
  chunk_size: 1024
  model: vits-zh-hf-theresa
  provider: cpu
  speed: 1.0

# 数据库配置
database:
  type: sqlite
  path: ./data/voiceapi_flow.db
  auto_create: true
  backup_enabled: true
  backup_interval: 86400  # 24小时

# 任务配置 - 简化的任务定义
task:
  name: "driving_evaluation"
  default_filename_template: "ai_result_{timestamp}.xlsx"
  score_mapping:
    "压力性": "Mental_Load"
    "可预测性": "Predictable"
    "响应性": "Timely_Response"
    "舒适性": "Comfort"
    "效率性": "Efficiency"
    "功能性": "Features"
    "安全性": "Safety"
